# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Enviar build para o time de testes no Testflight"
  lane :upload_to_testflight do
    build_app(scheme: "Reminder")
    upload_to_testflight
  end

  desc "Fazer upload de um .ipa já existente para o TestFlight"
  lane :upload_existing_ipa do
    upload_to_testflight(
      ipa: "/Users/mateuscoelho/Desktop/Reminder/Reminder.ipa",
      skip_waiting_for_build_processing: true 
    )
  end
end
